=== unicode-org/icu-docs/design/LocaleElements.dtd
<!ELEMENT Abbreviation ( #PCDATA ) >

<!ELEMENT Address ( #PCDATA ) >

<!ELEMENT AddressFormat ( PostalPattern ) >

<!ELEMENT Application ( #PCDATA ) >

<!ELEMENT Audience ( #PCDATA ) >

<!ELEMENT Contact ( #PCDATA ) >

<!ELEMENT CountryCar ( #PCDATA ) >

<!ELEMENT CountryISBNNumber ( #PCDATA ) >

<!ELEMENT CountryNumber ( #PCDATA ) >

<!ELEMENT CountryPost ( #PCDATA ) >

<!ELEMENT Date ( #PCDATA ) >

<!ELEMENT DomesticPattern ( #PCDATA ) >

<!ELEMENT Email ( #PCDATA ) >

<!ELEMENT Fax ( #PCDATA ) >

<!ELEMENT GeneralSalutation ( #PCDATA ) >

<!ELEMENT Height ( #PCDATA ) >

<!ELEMENT Identification ( Title| Source| Address| Contact| Email| Telephone| Fax| Language| Territory| Audience| Application| Abbreviation| Revision| Date )* >

<!ELEMENT InternationalDialCode ( #PCDATA ) >

<!ELEMENT InternationalPattern ( #PCDATA ) >

<!ELEMENT InternationalPrefix ( #PCDATA ) >

<!ELEMENT Language ( #PCDATA ) >

<!ELEMENT LanguageLibraryUse ( #PCDATA ) >

<!ELEMENT LongSalutationMiss ( #PCDATA ) >

<!ELEMENT LongSalutationMr ( #PCDATA ) >

<!ELEMENT LongSalutationMrs ( #PCDATA ) >

<!ELEMENT NameFormat ( NamePattern| GeneralSalutation| ShortSalutationMr| ShortSalutationMiss|ShortSalutationMrs| LongSalutationMr| LongSalutationMiss| LongSalutationMrs )* >

<!ELEMENT NamePattern ( #PCDATA ) >

<!ELEMENT PaperSize ( Height, Width, Units ) >

<!ELEMENT PosixCompatibilityData ( messages| AddressFormat| NameFormat| Identification| TelephoneFormat )* >

<!ELEMENT PostalPattern ( #PCDATA ) >

<!ELEMENT Revision ( #PCDATA ) >

<!ELEMENT ShortSalutationMiss ( #PCDATA ) >

<!ELEMENT ShortSalutationMr ( #PCDATA ) >

<!ELEMENT ShortSalutationMrs ( #PCDATA ) >

<!ELEMENT Source ( #PCDATA ) >

<!ELEMENT Telephone ( #PCDATA ) >

<!ELEMENT TelephoneFormat ( InternationalPattern| DomesticPattern| InternationalDialCode| InternationalPrefix )* >

<!ELEMENT Territory ( #PCDATA ) >

<!ELEMENT Title ( #PCDATA ) >

<!ELEMENT Units ( #PCDATA ) >

<!ELEMENT Width ( #PCDATA ) >

<!ELEMENT after ( #PCDATA ) >

<!ELEMENT normalization ( #PCDATA ) >

<!ELEMENT alternate ( #PCDATA ) >

<!ELEMENT vairableTop ( #PCDATA ) >

<!ELEMENT caseLevel ( #PCDATA ) >

<!ELEMENT caseFirst ( #PCDATA ) >

<!ELEMENT composition ( #PCDATA ) >

<!ELEMENT lt1 ( #PCDATA ) >

<!ELEMENT am ( #PCDATA ) >

<!ELEMENT boundaries ( grapheme| word| Sentence| Line )* >

<!ELEMENT TransliteratorNamePattern ( #PCDATA ) >

<!ELEMENT calendar ( am | dayAbbr | dayNames | eras | monthAbbr | monthNames | patterns | pm | week |firstDay |minDays )* >
<!ATTLIST calendar class NMTOKEN #REQUIRED >
<!ATTLIST calendar default NMTOKEN #IMPLIED >
<!ATTLIST calendar inheritsFrom NMTOKEN #IMPLIED >

<!ELEMENT calendars ( calendar+ ) >

<!ELEMENT chars ( #PCDATA ) >

<!ELEMENT city ( #PCDATA ) >

<!ELEMENT collation ( collationElements ) >
<!ATTLIST collation accentOrder NMTOKEN #REQUIRED >
<!ATTLIST collation override NMTOKEN #REQUIRED >
<!ATTLIST collation version NMTOKEN #REQUIRED >


<!ELEMENT collationElements ( after | eq | gt1 | gt2 | gt3 | normalization | alternate | vairableTop | caseLevel | caseFirst | lt1)* >

<!ELEMENT correspondsTo ( #PCDATA ) >
<!ATTLIST correspondsTo vendor NMTOKEN #REQUIRED >

<!ELEMENT countries ( country+ ) >

<!ELEMENT country ( #PCDATA ) >
<!ATTLIST country id NMTOKEN #REQUIRED >
<!ATTLIST country iso2 NMTOKEN #IMPLIED >
<!ATTLIST country iso3 NMTOKEN #IMPLIED >

<!ELEMENT currencies ( currency+ ) >

<!ELEMENT currency ( symbol| pattern| decimal| name |group )* >
<!ATTLIST currency default NMTOKEN #IMPLIED >
<!ATTLIST currency id NMTOKEN #REQUIRED >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT date ( full| long| medium| short )* >

<!ELEMENT dateTime ( #PCDATA ) >

<!ELEMENT day ( #PCDATA ) >
<!ATTLIST day id NMTOKEN #IMPLIED >

<!ELEMENT dayAbbr ( day+ ) >

<!ELEMENT dayNames ( day+ ) >

<!ELEMENT daylight ( #PCDATA ) >

<!ELEMENT decimal ( #PCDATA ) >

<!ELEMENT displayNames ( scripts| languages| countries| variants |localePatterns )* >

<!ELEMENT encodings ( mapping+ ) >
<!ATTLIST encodings requiredLetters NMTOKEN #REQUIRED >

<!ELEMENT eq ( #PCDATA ) >

<!ELEMENT era ( #PCDATA ) >
<!ATTLIST era id NMTOKEN #REQUIRED >

<!ELEMENT eras ( era+ ) >

<!ELEMENT exponential ( #PCDATA ) >

<!ELEMENT firstDay ( #PCDATA ) >

<!ELEMENT full ( #PCDATA ) >

<!ELEMENT generic ( #PCDATA ) >

<!ELEMENT grapheme ( #PCDATA ) >
<!ATTLIST grapheme class NMTOKEN #REQUIRED >

<!ELEMENT group ( #PCDATA ) >

<!ELEMENT gt1 ( #PCDATA ) >

<!ELEMENT gt2 ( #PCDATA ) >

<!ELEMENT gt3 ( #PCDATA ) >

<!ELEMENT identity ( language| country| variant| correspondsTo )* >

<!ELEMENT infinity ( #PCDATA ) >

<!ELEMENT language ( #PCDATA ) >
<!ATTLIST language id NMTOKEN #REQUIRED >
<!ATTLIST language iso2 NMTOKEN #IMPLIED >
<!ATTLIST language iso3 NMTOKEN #IMPLIED >

<!ELEMENT languages ( language+ ) >

<!ELEMENT list ( #PCDATA ) >

<!ELEMENT locale ( #PCDATA ) >

<!ELEMENT localeData ( versioning | identity| orientation| encodings| displayNames | calendars | numberFormat | currencies | collation | timeZoneNames | boundaries | measurement | CountryPost | CountryNumber | CountryCar | CountryISBNNumber | LanguageLibraryUse | PaperSize | PosixCompatibilityData|TransliteratorNamePattern )* >

<!ELEMENT localePatterns ( locale, list, composition ) >

<!ELEMENT long ( #PCDATA | daylight | generic | standard )* >

<!ELEMENT mapping ( #PCDATA ) >
<!ATTLIST mapping name NMTOKEN #REQUIRED >

<!ELEMENT measurement ( #PCDATA ) >

<!ELEMENT medium ( #PCDATA ) >

<!ELEMENT messages ( no| yes| shortYes| shortNo )* >

<!ELEMENT minDays ( #PCDATA ) >

<!ELEMENT minusSign ( #PCDATA ) >

<!ELEMENT month ( #PCDATA ) >
<!ATTLIST month id NMTOKEN #REQUIRED >

<!ELEMENT monthAbbr ( month+ ) >

<!ELEMENT monthNames ( month+ ) >

<!ELEMENT nan ( #PCDATA ) >

<!ELEMENT nativeZeroDigit ( #PCDATA ) >

<!ELEMENT no ( #PCDATA ) >

<!ELEMENT numberFormat ( patterns| symbols )* >
<!ATTLIST numberFormat class NMTOKEN #REQUIRED >
<!ATTLIST numberFormat default NMTOKEN #REQUIRED >

<!ELEMENT orientation ( #PCDATA ) >
<!ATTLIST orientation characters NMTOKEN #REQUIRED >
<!ATTLIST orientation lines NMTOKEN #REQUIRED >

<!ELEMENT pattern ( #PCDATA ) >

<!ELEMENT patternDigit ( #PCDATA ) >

<!ELEMENT patterns ( chars| time| date| dateTime?| decimal?| percent?| scientific? )* >

<!ELEMENT perMille ( #PCDATA ) >

<!ELEMENT percent ( #PCDATA ) >

<!ELEMENT percentSign ( #PCDATA ) >

<!ELEMENT plusSign ( #PCDATA ) >

<!ELEMENT pm ( #PCDATA ) >

<!ELEMENT scientific ( #PCDATA ) >

<!ELEMENT script ( #PCDATA ) >
<!ATTLIST script id NMTOKEN #REQUIRED >

<!ELEMENT scripts ( script+ ) >

<!ELEMENT short ( #PCDATA | daylight | generic | standard )* >

<!ELEMENT shortNo ( #PCDATA ) >

<!ELEMENT shortYes ( #PCDATA ) >

<!ELEMENT standard ( #PCDATA ) >

<!ELEMENT symbol ( #PCDATA ) >

<!ELEMENT symbols ( decimal, group, list, percentSign, nativeZeroDigit, patternDigit, plusSign, minusSign, exponential, perMille, infinity, nan )* >

<!ELEMENT time ( #PCDATA | full | long | medium | short )* >

<!ELEMENT timeZoneNames ( zone+ ) >

<!ELEMENT variant ( #PCDATA ) >
<!ATTLIST variant id NMTOKEN #REQUIRED >

<!ELEMENT variants ( variant ) >

<!ELEMENT version ( #PCDATA ) >
<!ATTLIST version date CDATA #IMPLIED>
<!ATTLIST version number NMTOKEN #REQUIRED >

<!ELEMENT versioning ( version+ ) >

<!ELEMENT week ( minDays, firstDay, weekendStart, weekendEnd ) >

<!ELEMENT weekendEnd ( day, time ) >

<!ELEMENT weekendStart ( day, time ) >

<!ELEMENT word ( #PCDATA ) >
<!ATTLIST word class NMTOKEN #REQUIRED >

<!ELEMENT Line ( #PCDATA ) >
<!ATTLIST Line class NMTOKEN #REQUIRED >

<!ELEMENT Sentence ( #PCDATA ) >
<!ATTLIST Sentence class NMTOKEN #REQUIRED >

<!ELEMENT yes ( #PCDATA ) >

<!ELEMENT zone ( city | long | short )* >
<!ATTLIST zone default NMTOKEN #IMPLIED >
<!ATTLIST zone id CDATA #REQUIRED >

=== unicode-org/icu-docs/design/LocaleElements.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE LocaleElements SYSTEM "./LocaleElements.dtd" >-->
<localeData>
<!--
Locale Data Format
Draft: 2000-06-16

Format that contains the required locale data for use by Java, ICU and POSIX APIs.
Note: constructing a POSIX locale also requires use of the Unicode Character Database data.
That data being common across locales, it is not duplicated here.
See ftp://ftp.unicode.org/Public/UNIDATA/UnicodeCharacterDatabase.html.

NOTE: The data below is purely illustrative, and doesn't match any particular language.
NOTE: The data for any given locale will only contain items that are different from the parent locale.
For example, most country locales will inherit the bulk of their data from the language locale: 
"en" will contain the bulk of the data: en_US will only contain a few items like currency.
-->
    <versioning>
      <version number="1.1">Various notes and changes in version 1.1</version>
      <version number="1.0">Various notes and changes in version 1.0</version>
    </versioning>

     <identity>
        <!-- Two letter codes, if available; otherwise 3-letter codes.
             If both exist, a separate database contains the mapping. -->
        <language id="en" />
        <country id="US" />

        <!-- Only one variant allowed for now -->
	   <variant id="B"/> 
        <correspondsTo vendor="windows">0409</correspondsTo>
     </identity>

       <orientation lines="top-to-bottom" characters="left-to-right" />    <!-- both attributes are required -->

    <encodings requiredLetters="a-z&#xE5;&#xE6;&#xF8;">    <!-- optional attribute -->
        <!--
        List of encodings that are in common use in this locale.
        The order is not significant.
        The format is as in http://www.unicode.org/unicode/reports/tr22/
        with the version suppressed.
        (It is assumed that the largest available version is chosen.)
        The required letters can also be used to select appropriate encodings.
        -->
       <mapping>windows-1252</mapping>
       <mapping>iso-8859_1</mapping>
       <mapping>euc-jp</mapping>
    </encodings>

    <!--
    Display names for scripts, languages, countries, and variants in this locale
    -->
    <displayNames>
        <scripts>
            <!-- IDs come from the Unicode Tech Report on scripts -->
            <script id="Latin">Romana</script>
            <script id="Cyrillic">Kyrillica</script>
         </scripts>
    
        <languages>
            <language id="ab">Abkhazian</language>
            <language id="aa">Afar</language>
            <language id="af">Afrikaans</language>
            <language id="sq">Albanian</language>
        </languages>
    
        <countries>
            <country id="AF">Afghanistan</country>
            <country id="AL">Albania</country>
            <country id="DZ">Algeria</country>
            <country id="AD">Andorra</country>
            <country id="AO">Angola</country>
			<country id="US">United States</country>
        </countries>
    
		<!-- Variant IDs must be unique across ALL locales. Currently they include
				B, NY, EURO -->
        <variants>
            <variant id="B">Bokm&#x00e5;l</variant>
        </variants>
    
        <!--
        Java/ICU choice format syntax for producing the name of a locale in a particular language.
        -->
        <localePatterns>
			<locale>{0,choice,0#|1#{1}|2#{1} ({2})}</locale>
            <list>{0,choice,0#|1#{1}|2#{1},{2}|3#{1},{2},{3}}</list>
            <composition>{0},{1}</composition>
		</localePatterns>
    </displayNames>
<!--
There can be multiple calendars in the same locale, e.g. Gregorian + Imperial Japanese.
The ids must match what is produced by the calendar system.
-->
  <calendars>
    <calendar class="Gregorian" default="true">
        <monthNames>
			<month id="1">January</month>
            <month id="2">February</month>
            <month id="3">March</month>
            <month id="4">April</month>
            <month id="5">May</month>
            <month id="6">June</month>
            <month id="7">July</month>
            <month id="8">August</month>
            <month id="9">September</month>
            <month id="10">October</month>
            <month id="11">November</month>
            <month id="12">December</month>
		</monthNames>
		<monthAbbr>
			<month id="1">Jan</month>
            <month id="2">Feb</month>
            <month id="3">Mar</month>
            <month id="4">Apr</month>
            <month id="5">May</month>
            <month id="6">Jun</month>
            <month id="7">Jul</month>
            <month id="8">Aug</month>
            <month id="9">Sep</month>
            <month id="10">Oct</month>
            <month id="11">Nov</month>
            <month id="12">Dec</month>
		</monthAbbr>		
		
        <dayNames>
			<day id="SUN">Sunday</day>
            <day id="MON">Monday</day>
            <day id="TUE">Tuesday</day>
            <day id="WED">Wednesday</day>
            <day id="THU">Thursday</day>
            <day id="FRI">Friday</day>
            <day id="SAT">Saturday</day>
		</dayNames>
		<dayAbbr>
			<day id="SUN">Sun</day>
            <day id="MON">Mon</day>
            <day id="TUE">Tue</day>
            <day id="WED">Wed</day>
            <day id="THU">Thu</day>
            <day id="FRI">Fri</day>
            <day id="SAT">Sat</day>
		</dayAbbr>
        <week>
            <minDays>1</minDays>
            <firstDay>SUN</firstDay>
            <weekendStart><day>FRI</day><time>18:00</time></weekendStart>
            <weekendEnd><day>SUN</day><time>18:00</time></weekendEnd>
        </week>
        <am>AM</am><pm>PM</pm>
        <eras>
            <!-- Non-gregorians may have many more eras -->
               <era id="0">BC</era>
               <era id="1">AD</era>
        </eras>
        <!--
        Patterns used for formatting and parsing dates and times for this calendar
        -->
        <patterns>
            <chars>GyMdkHmsSEDFwWahKz</chars>
             <time>
			 	<full>h:mm:ss a z</full>
                <long>h:mm:ss a z</long>
                <medium>h:mm:ss a</medium>
                <short>h:mm a</short>
				</time>
             <date>
                <full>EEEE, MMMM d, yyyy</full>
                <long>MMMM d, yyyy</long>
                <medium>MMM d, yyyy</medium>
                <short>M/d/yy</short>
			  </date>
             <dateTime>{0} {1}</dateTime>
        </patterns>
    </calendar>

	<!-- The Buddhist calendar inherits month names, etc. (everything but eras) from Gregorian -->
    <calendar class="Buddhist" inheritsFrom="Gregorian">
        <eras>
               <era id="0">BE</era>
        </eras>
    </calendar>
   </calendars>     
 <!--
There can be multiple number formats for the same locale.
Only one can be marked as "default"
-->
   <numberFormat class="decimal" default="true">
       <patterns>
        <decimal>#,##0.###;-#,##0.###</decimal>
        <percent>#,##0%</percent>
        <scientific>0E##</scientific>
    </patterns>
      <symbols>
          <decimal>.</decimal>
          <group>,</group>
          <list>;</list>
          <percentSign>%</percentSign>
          <nativeZeroDigit>0</nativeZeroDigit>
          <patternDigit>#</patternDigit>
          <plusSign>+</plusSign>
          <minusSign>-</minusSign>
          <exponential>E</exponential>
          <perMille>&#x2030;</perMille>
          <infinity>&#x221e;</infinity>
          <nan>&#x2639;</nan>
       </symbols>
    </numberFormat>

    <currencies>
        <currency id="USD" default="true">
            <symbol>$</symbol>
            <pattern>¤ #,##0.00;(¤ #,##0.00)</pattern>
            <decimal>.</decimal>
        </currency>
        <currency id ="JAY">
            <name>¥</name>
            <pattern>¤ #,##0;(¤ #,##0)</pattern>
            <decimal>.</decimal>
        </currency>
    </currencies>


    <!--
    This syntax is an XMLized version of the Java/ICU syntax, used to tailor the default table.
    The main difference is that the < sign is replaced by «, and the & is replaced by "§",
    since otherwise the XML is clumsy!

    Note that collation needs its own version, independent of the Locale version. 
    For more information, see 
    http://java.sun.com/products/jdk/1.2/docs/api/java/text/RuleBasedCollator.html
    and
    http://www.unicode.org/unicode/reports/tr10/#Comparison to Java.
    By default, lowercase is before upper in the default.
    This can be changed with the firstCase="upper" attribute.
    French accent ordering can be specified with the accentOrder="reverse" attribute.
    The displayName attribute supplies a message pattern for getDisplayName.
    -->
    <collation version="1.5" accentOrder="reverse" override="true">
        a,A « b,B « c,C
		§ C « ch « D
    </collation>

    <timeZoneNames>
        <!--
        The zone id's are language-independent.
        Their values and data (default offset from GMT, daylight savings rules)
        are stored elsewhere
        Here we just have the localized names for them.
        -->
		<zone id="America/Los_Angeles" default="true">
			<long>
				<generic>Pacific Time</generic>
				<standard>Pacific Standard Time</standard>
				<daylight>Pacific Daylight Time</daylight>
			</long>
			<short>
				<generic>PT</generic>
				<standard>PST</standard>
				<daylight>PDT</daylight>
			</short>
			<city>Los Angeles</city>
		</zone>
		
        <zone id="America/Denver">
            <long>
				<generic>Mountain Time</generic>
				<standard>Mountain Standard Time</standard>
				<daylight>Mountain Daylight Time</daylight>
			</long>
            <short>
				<generic>MT</generic>
				<standard>MST</standard>
				<daylight>MDT</daylight>
			</short>
            <city>Denver</city>
        </zone>
		
        <zone id="Europe/London">
            <long>
				<generic>British Time</generic>
				<standard>British Standard Time</standard>
				<daylight>British Daylight Time</daylight>
			</long>
